name: Build and Tests

on:  
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:  
  build:    
    runs-on: windows-latest
    
    steps:      
      - uses: actions/checkout@v2
      
      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1

      - name: Setup NuGet
        uses: NuGet/setup-nuget@v1.0.5
        
      - name: Setup VSTest
        uses: darenm/Setup-VSTest@v1

      - name: Navigate to Workspace
        run: cd $GITHUB_WORKSPACE

      - name: Restore Packages
        run: nuget restore TDD_Ahorcado.sln

      - name: Build Solution
        run: |
          msbuild.exe TDD_Ahorcado.sln /p:platform="Any CPU" /p:configuration="Release"
        
      - name: Run Tests
        run: vstest.console.exe .\UnitTestings\bin\Release\UnitTestings.dll
        
  deploy:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: build and push to docker
      uses: docker/build-push-actions@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: ${{ github.repository }}
        tag_with_ref: true
        tag_with_sha: true
        tag: ${{ github.sha }}
    
